export const SET_APP_VIEW_MODE = 'SET_APP_VIEW_MODE';
export const SORT_LIST_BY = 'SORT_LIST_BY';
export const GET_USER_GEOLOCATION = 'GET_USER_GEOLOCATION';
export const GET_LAST_UPDATE = 'GET_LAST_UPDATE';
export const UPDATE_LAKES_TEMPERATURE = 'UPDATE_LAKES_TEMPERATURE';
export const UPDATE_LAKES_DISTANCE = 'UPDATE_LAKES_DISTANCE';
export const GET_NEAREST_LAKE = 'GET_NEAREST_LAKE';

export const FETCH_LAKES_START = 'FETCH_LAKES_START';
export const FETCH_LAKES_SUCCESS = 'FETCH_LAKES_SUCCESS';
export const FETCH_LAKES_FAIL = 'FETCH_LAKES_FAIL';